### ISSUE TITLE
Weather details not seeing 

### ISSUE THREAD

**Issue by arti-karnik** [JoeDonMalone/Project-1-Group-4#34]
Steps: 
1. Go to Application
2. Check on top-right side and check weather details
Actual :  Default temperature, icon and description seen 
Expected : Correct temperature, icon and description should be seen 

code : script.js callWeatherInfo( latitude, longitude )
![image](https://user-images.githubusercontent.com/75514762/107267647-0e729f00-69fc-11eb-92a0-7a3af59720c8.png)

**Comment by ktkyletran** [comment]
I fixed this but I havent pushed code yet

**Comment by arti-karnik** [comment]
Thanks @ktkyletran
